DROP TABLE prescription;
DROP TABLE medicament;
DROP TABLE rdv;
DROP TABLE patient;
DROP TABLE medecin;
DROP TABLE assurance;
DROP TABLE specialite;
DROP TABLE personne;
DROP TYPE "type";
DROP TYPE "motif";
DROP TYPE "sexe";
DROP ROLE secretaire;
DROP ROLE medecin;
DROP ROLE administrateur;
DROP USER lucie CASCADE;
DROP USER marie CASCADE;
DROP USER julie CASCADE;